import type { Metadata } from "next";
import { Bellefair } from "next/font/google";


import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const bellefair = Bellefair({
  subsets: ["latin"],
  weight: ["400"],

});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bellefair.className}`}     
      > 
        {children}  
      </body>
    </html>
  );
}
